// <auto-generated />
using System;
using DiaryAPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryAPP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryAPP.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hiking",
                            Created = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Go on Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Shop",
                            Created = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Go on Shopping"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Ski",
                            Created = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Go on Skiing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
